name: Build
env:
  NODE_VERSION: 14.18.1

on:
  push:
    branches:
      - "*"

jobs:
  bundle:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            buildFolder: bundle/deb
            ext: "_amd64.deb"
            compressed: ""
          - platform: macos-latest
            buildFolder: bundle/dmg
            ext: ".dmg"
            compressed: ""
          - platform: windows-latest
            buildFolder: "bundle/msi"
            ext: "_x64.msi"
            compressed: ""
    steps:
      - uses: actions/checkout@v2
      - name: Extract Version from Tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Extract Version from Commit
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - run: yarn
      - run: cargo update
        working-directory: src-tauri

      - name: build
        run: yarn tauri build
        env:
          CI: true
          ENABLE_CODE_SIGNING: ${{ secrets.MACOS_SIGN_CERTIFICATE }}
          APPLE_CERTIFICATE: ${{ secrets.MACOS_SIGN_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_SIGN_CERTIFICATE_PASSPHRASE }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.MACOS_APPLE_SIGNING_IDENTITY }}
          APPLE_PROVIDER_SHORT_NAME: ${{ secrets.MACOS_APPLE_PROVIDER_SHORT_NAME }}
          APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.MACOS_APPLE_PASSWORD }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}

      - name: Publish Snapshot Artifact
        uses: actions/upload-artifact@v2
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          name: ${{ format('snapshot-{0}', matrix.platform ) }}
          path: ${{ format('./src-tauri/target/release/{0}/*{1}', matrix.buildFolder, matrix.ext ) }}
          retention-days: 5
