name: Release
env:
  NODE_VERSION: 14.18.1

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1
        with:
          draft: true

  bundle:
    needs:
      - create-release-draft
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            buildFolder: deb
            extension: deb
          - platform: macos-latest
            buildFolder: dmg
            extension: dmg
          - platform: windows-latest
            buildFolder: msi
            extension: msi
    steps:
      - uses: actions/checkout@v2
      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - run: yarn
      - run: cargo update
        working-directory: src-tauri

      # Temporary:
      - run: yarn build
      - run: |
          cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch next
        working-directory: src-tauri
      ## END TEMPORARY

      - name: build
        #run: yarn tauri build
        run: cargo tauri build
        working-directory: src-tauri
        env:
          CI: true
          ENABLE_CODE_SIGNING: ${{ secrets.MACOS_SIGN_CERTIFICATE }}
          APPLE_CERTIFICATE: ${{ secrets.MACOS_SIGN_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_SIGN_CERTIFICATE_PASSPHRASE }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.MACOS_APPLE_SIGNING_IDENTITY }}
          APPLE_PROVIDER_SHORT_NAME: ${{ secrets.MACOS_APPLE_PROVIDER_SHORT_NAME }}
          APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.MACOS_APPLE_PASSWORD }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: ${{ format('./src-tauri/target/release/bundle/{0}/*.{1}', matrix.buildFolder, matrix.extension) }}
